name: Your New Jekyll Site
markdown: redcarpet
pygments: true
safe: true
lsi: false
excerpt_separator: "<BREAK>"
url: 'http://elifitch.github.io'
# url: 'http://www.elifitch.com'
# source: elifitch.github.io